// Automatically generated by the Flatbuffers compiler. Do not modify.
pub mod suspect {
    use super::*;
    mod mood_generated;
    pub use self::mood_generated::*;
    mod position_generated;
    pub use self::position_generated::*;
    mod location_generated;
    pub use self::location_generated::*;
    mod suspect_generated;
    pub use self::suspect_generated::*;
} // suspect
